config/routes.rb
Rails.application.routes.draw do
  get("/", { :controller => "places", :action => "index" })
  resources "entries"
  resources "places"
  resources "sessions"
  resources "users"

  get("/login", :controller => "sessions", :action => "new")
  get("/logout", :controller => "sessions", :action => "destroy")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_one_attached :uploaded_image
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :user

  def user
    puts "------------------ code before every request ------------------"
    @user = User.find_by({ "id" => session["user_id"] })
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def show
    @entry = Entry.find_by({"id" => params["id"]})
    @place = Place.find_by({"id" => @entry["place_id"]})
  end

  def new
    @entry = Entry.new
    @place = Place.find_by({ "id" => params["place_id"] })
  end

  def create
    @entry = Entry.new
    @entry["title"] = params["title"]
    @entry["description"] = params["description"]
    @entry["occurred_on"] = params["occurred_on"]
    @entry["place_id"] = params["place_id"]
    @entry.uploaded_image.attach(params["uploaded_image"])
    @entry["user_id"] = @user["id"]
    @entry.save
    redirect_to "/places/#{@entry["place_id"]}"
  end

  before_action :allow_cors
  def allow_cors
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, PATCH, DELETE, OPTIONS'
    response.headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token, Auth-Token, Email, X-User-Token, X-User-Email'
    response.headers['Access-Control-Max-Age'] = '1728000'
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find_by({ "id" => params["id"] })
    @entries = Entry.where({ "place_id" => @place["id"], "user_id" => session["user_id"]})    
  end

  def new
  end

  def create

    if User.find_by({ "id" => session["user_id"] }) != nil
      @place = Place.new
      @place["name"] = params["name"]
      @place.save
    else
      flash["notice"] = "Login first."
    end
    redirect_to "/places"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by({ "email" => params["email"] })
    if @user != nil
      if BCrypt::Password.new(@user["password"]) == params["password"]
        session["user_id"] = @user["id"]
        flash["notice"] = "Welcome."
        redirect_to "/places"
      else
        flash["notice"] = "Nope."
        redirect_to "/login"
      end
    else
      flash["notice"] = "Nope."
      redirect_to "/login"
    end
  end

  def destroy
    session["user_id"] = nil
    flash["notice"] = "Goodbye."
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by({ "id" => params["id"] })
  end
 
  def new
  end

  def create
    if User.find_by({ "email" => params["email"] }) == nil
      @user = User.new
      @user["username"] = params["username"]
      @user["email"] = params["email"]
      @user["password"] = BCrypt::Password.create(params["password"])
      @user.save
      redirect_to "/login"
    else
      flash["notice"] = "Email taken."
      redirect_to "/users/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry</h1>

<form action="/entries" method="post" enctype="multipart/form-data">

  <input type="hidden" name="place_id" value="<%= params["place_id"] %>">

  <p>
    <label for="title_input">Title</label>
    <input type="text" name="title" id="title_input">
  </p>

  <p>
    <label for="description_input">Description</label>
    <input type="text" name="description" id="description_input">
  </p>

  <p>
    <label for="occurred_on_input">Occurred On</label>
    <input type="date" name="occurred_on" id="occurred_on_input">
  </p>

  <div class="mb-3">
      <label for="uploaded_image_input" class="form-label">Upload Image</label>
      <input type="file" name="uploaded_image" id="uploaded_image_input" class="form-control">
    </div>
    
  <button>Save</button>
</form>

app/views/entries/show.html.erb
<!-- Entry details page -->


<h1><%= @entry["title"] %>, <%= @entry["title"] %></h1>

<ul>
  <li><%= @entry["description"] %>, <%= @entry["description"] %></li>
  <li><%= @entry["posted_on"] %></li>
</ul>



<p><a href="/places/<%= @place["id"] %>">Back to<%= @place["name"] %></a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <title>Places</title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Bootstrap Icons -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="/stylesheets/application.css">

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/places">Home</a>
          </li>
        </ul>
        
        <ul class="navbar-nav mb-2 mb-lg-0">
          <% @user = User.find_by({ "id" => session["user_id"] }) %>
          <% if @user == nil %>
            <li class="nav-item">
              <a href="/users/new" class="nav-link">Sign Up</a>
            </li>
            <li class="nav-item">
              <a href="/login" class="nav-link">Login</a>
            </li>
          <% else %>
            <li class="navbar-text">
              Logged in as: <%= @user["username"] %>
              |
            </li>
            <li class="nav-item">
              <a href="/logout" class="nav-link">Logout</a>
            </li>
            
          <% end %>
        </div>
  
      </div>
    </div>
  </nav>

  <div class="container mt-3">
    <% if flash["notice"] != nil %>
      <div class="alert alert-primary">
        <%= flash["notice"] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

    

<% if User.find_by({ "id" => session["user_id"] }) != nil %>
<ul>
  <% for place in @places %>
    <li><a href="/places/<%= place["id"] %>"><%= place["name"] %></a></li>
  <% end %>
</ul>

<p>
  <a href="/places/new">New place</a>
</p>

<% else %>
  <p>You must first <%= link_to "login", login_path %> to see Places.</p>
<% end %>

app/views/places/new.html.erb
<h1>New Place</h1>

<form action="/places" method="post">
  <p>
    <label for="name_input">Name</label>
    <input type="text" name="name" id="name_input">
  </p>

  <button>Save</button>
      <a href="/places">Cancel</a>
</form>

app/views/places/show.html.erb
<h1><%= @place["name"] %></h1>

<h2>My Entries</h2>
<ul>

<div class="container text-center">
  <div class="row pt-3">
  
<% for entry in @entries %>

  <div class="col-md-4 pt-3">

     <h3> <%= entry["title"] %> </h3>
     <h6> <%= entry["occurred_on"] %> </h6>
      <%= entry["description"] %>
       
<% if entry.uploaded_image.attached? %>
  <img src="<%= url_for(entry.uploaded_image) %>" class="img-fluid">
<% else %>
  <img src="<%= entry["image"] %>" class="img-fluid">
<% end %>
 </div>
  <% end %>
</ul>

<p>
  <a href="/entries/new?place_id=<%= @place["id"] %>">New Entry</a>
</p>

<p>
  <a href="/places">Back to All Places</a>
</p>

app/views/users/new.html.erb
<h1>New User Account</h1>

<form action="/users" method="post">

  <p>
    <label for="username_input">Username</label>
    <input type="text" name="username" id="username_input">
  </p>
  <p>
    <label for="email_input">Email</label>
    <input type="text" name="email" id="email_input">
  </p>
  <p>
    <label for="password_input">Password</label>
    <input type="password" name="password" id="password_input">
  </p>

  <button>Signup</button>
</form>